---
galaxy_info:
  author: Homelab Project
  description: Mailcow Dockerized mail server
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - mail
    - docker
    - mailcow

dependencies: []
