---
- name: Import Alloy validation tasks
  ansible.builtin.import_tasks: validate.yaml

- name: Import Alloy installation tasks
  ansible.builtin.import_tasks: install.yaml

- name: Import Alloy secrets management tasks
  ansible.builtin.import_tasks: secrets.yaml

- name: Import Alloy configuration tasks
  ansible.builtin.import_tasks: configure.yaml
