---
- name: Run custom scripts
  ansible.builtin.shell:
    cmd: |
      export HOME="{{ dotfiles_user_home }}"
      cd "{{ dotfiles_user_dest }}"
      {{ item }}
  loop: "{{ dotfiles_custom_scripts }}"
  register: dotfiles_custom_script_output
  changed_when: dotfiles_custom_script_output.rc == 0
  failed_when: dotfiles_custom_script_output.rc != 0
  loop_control:
    label: "{{ item }}"
