---
- name: Restart technitium
  community.docker.docker_compose_v2:
    project_src: "{{ dns_server_install_dir }}"
    state: present
    recreate: always

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  become: true
