---
galaxy_info:
  author: wookiesh
  description: Mailpit SMTP catch-all and email testing tool
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
