---
- name: deploy portainer
  ansible.builtin.command: docker stack deploy -c stack.yaml portainer
  args:
    chdir: "{{ portainer_install_dir }}"
  run_once: true
  delegate_to: "{{ docker_swarm_manager }}"
  when: portainer_deployment_mode == "stack"
