---
- name: Create Portainer install directory
  ansible.builtin.file:
    path: "{{ portainer_install_dir }}"
    state: directory
    owner: root
    group: "{{ docker_host_services_group | default('docker') }}"
    mode: "2775"
  become: true

- name: Deploy Portainer stack/compose file
  ansible.builtin.template:
    src: "{{ portainer_deployment_mode }}.yaml.j2"
    dest: "{{ portainer_install_dir }}/stack.yaml"
    owner: root
    group: "{{ docker_host_services_group | default('docker') }}"
    mode: "0640"
  become: true
  when: portainer_deployment_mode == "compose" or inventory_hostname == docker_swarm_manager
  notify: Deploy Portainer stack
