---
- name: Import keepalived validation tasks
  ansible.builtin.import_tasks: validate.yaml

- name: Import keepalived installation tasks
  ansible.builtin.import_tasks: install.yaml

- name: Import keepalived configuration tasks
  ansible.builtin.import_tasks: configure.yaml

- name: Import keepalived service tasks
  ansible.builtin.import_tasks: service.yaml

- name: Import keepalived post-configuration tasks
  ansible.builtin.import_tasks: post_configure.yaml
