---
galaxy_info:
  author: wookiesh
  description: Technitium DNS server deployed via Docker Compose
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
