---
- name: Restart Traefik (Compose mode)
  ansible.builtin.command:
    cmd: "docker compose -f {{ traefik_compose_file }} restart"
  become: true
  changed_when: false
  when: traefik_deployment_mode == "compose"

- name: Restart Traefik (Swarm mode)
  ansible.builtin.command:
    cmd: "docker service update traefik_proxy --force"
  become: true
  changed_when: false
  when: traefik_deployment_mode == "swarm"
