---
admin_user_enabled: true
admin_user_name: ""
admin_user_shell: /bin/bash
admin_user_groups: ["sudo"]
admin_user_ssh_key: ""
admin_user_password_hash: ""

# OS-specific packages
admin_user_packages_debian:
  - "zsh"
  - "bat" # installs as batcat on Ubuntu/Debian
  - "curl"
  - "dnsutils"
  - "duf"
  - "fio"
  - "git"
  - "htop"
  - "highlight"
  - "iftop"
  - "iotop"
  - "iperf3"
  - "lsof"
  - "multitail"
  - "ncdu"
  - "net-tools"
  - "nload"
  - "strace"
  - "sudo"
  - "tree"
  - "unzip"
  - "vim"
  - "wget"

admin_user_packages_redhat:
  - "zsh"
  - "bat"
  - "curl"
  - "bind-utils" # dnsutils equivalent
  - "duf"
  - "fio"
  - "git"
  - "htop"
  - "highlight"
  - "iftop"
  - "iotop"
  - "iperf3"
  - "lsof"
  - "multitail"
  - "ncdu"
  - "net-tools"
  - "nload"
  - "strace"
  - "sudo"
  - "tree"
  - "unzip"
  - "vim"
  - "wget"

admin_user_packages_arch:
  - "zsh"
  - "bat"
  - "curl"
  - "bind-tools" # dnsutils equivalent
  - "duf"
  - "fio"
  - "git"
  - "htop"
  - "highlight"
  - "iftop"
  - "iotop"
  - "iperf3"
  - "lsof"
  - "multitail"
  - "ncdu"
  - "net-tools"
  - "nload"
  - "strace"
  - "sudo"
  - "tree"
  - "unzip"
  - "vim"
  - "wget"
