---
- name: Deploy Beszel stack
  ansible.builtin.command: docker stack deploy -c stack.yaml beszel
  args:
    chdir: "{{ beszel_install_dir }}"
  register: beszel_handler_result
  changed_when: ((beszel_handler_result.stdout | default('')) | regex_search('(Updating|Creating)')) is not none
  when:
    - beszel_deployment_mode == "stack"
    - inventory_hostname == docker_swarm_manager
