---
- name: Create Beszel install directory
  ansible.builtin.file:
    path: "{{ beszel_install_dir }}"
    state: directory
    owner: root
    group: "{{ docker_host_services_group | default('docker') }}"
    mode: "2775"
  become: true

- name: Deploy Beszel stack/compose file
  ansible.builtin.template:
    src: "{{ beszel_deployment_mode }}.yaml.j2"
    dest: "{{ beszel_install_dir }}/stack.yaml"
    owner: root
    group: "{{ docker_host_services_group | default('docker') }}"
    mode: "0640"
  become: true
  when: beszel_deployment_mode == "compose" or inventory_hostname == docker_swarm_manager
  notify: Deploy Beszel stack
