---
galaxy_info:
  author: wookiesh
  description: Outline wiki (compose) with Postgres and Redis
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
